[package]
org = "xlibb"
name = "graphql_schema_registry"
version = "@toml.version@"
authors = ["Ballerina"]
export=["graphql_schema_registry"]
keywords = ["graphql", "federation", "schema registry"]
repository = "https://github.com/xlibb/graphql-schema-registry"
license = ["Apache-2.0"]
distribution = "2201.6.0"